### ISSUE TITLE
sudo output not necessarily in english

### ISSUE THREAD

**Issue by andiries** [profesorfalken/jHardware#1]
On a linux machine where sudo output is not english (e.g. variable _LANG_ is set to _de_DE.UTF-8_), the method HardwareInfoUtils.isSudo() does not work properly

**Comment by profesorfalken** [comment]
Hi, 

It is extrange. In may case it does not change and my LANG in not english.

[~]$ sudo -n true
sudo: a password is required
[~]$ locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"

What is your output if you do "sudo -n true"?

Thanks

**Comment by andiries** [comment]
Hi Javier,

on a suse linux (openSuSE 13.2 (x64)) of a colleague of mine, LANG is set to de_DE.UTF-8. This is what he tells me about sudo:
sudo -n true: sudo: Ein Passwort ist notwendig
sudo -V: Sudo-Version 1.8.10p3
Sudoers Policy-Plugin Version 1.8.10p3
Sudoers-Datei Grammatik-Version 43
Sudoers I/O plugin version 1.8.10p3

**Comment by andiries** [comment]
Ah. I just found this. Didn't try it yet
http://askubuntu.com/questions/357220/how-to-check-if-sudo-password-has-been-entered-for-this-terminal-session

**Comment by andiries** [comment]
Actually after submitting _sudo -n true_ in bash, the return value is 1, when a password has to be provided. Otherwise it's 0.
Maybe that helps

**Comment by profesorfalken** [comment]
Ok,  I will try the 'return value' approach this evening. I will keep you updated.

Thank you!

**Comment by profesorfalken** [comment]
Hi Andreas. 
Finally I developed another solution, based on output, which is empty in the case of sudo. 

It will take a bit in order to be ready on Maven Central but you can already find the new version here: 
https://oss.sonatype.org/content/groups/staging/org/jhardware/jHardware/0.6.1/jHardware-0.6.1.jar

Tell me if it works OK now.

Thank you

**Comment by andiries** [comment]
Hi Javier, just a short heads up:
The problem on my colleagues machine is still there (Version 0.6.1). But actually I think your fix should be working. So we will find out why it's not working on his machine and let you know. But this might take some days, because we are quite busy with other stuff right now. Sorry.

**Comment by andiries** [comment]
Hi Javier,
issue is fixed.
Thanks, Andi

**Comment by profesorfalken** [comment]
Cool, I am glad it is fixed
